#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Consultas SQL para el módulo Welivery

# Consulta para obtener pedidos pendientes de envio con método FLEX y sin número de seguimiento
QRY_GET_PEDIDOS_PENDIENTES = """
SELECT A.NRO_PEDIDO, B.ORDER_ID_TIENDA, A.TALON_PED 
FROM SEIN_TABLA_TEMPORAL_SCRIPT AS A
LEFT JOIN GVA21 AS B ON B.NRO_PEDIDO=A.NRO_PEDIDO AND B.TALON_PED=A.TALON_PED
WHERE A.TALON_PED = '99'
AND A.METODO_ENVIO = 'FLEX'
AND A.NUM_SEGUIMIENTO IS NULL
AND COD_TRANSP = '0135'
ORDER BY A.NRO_PEDIDO DESC
"""

# Consulta para obtener pedidos pendientes de entrega (con número de seguimiento pero sin estado final)
QRY_GET_PEDIDOS_PENDIENTES_ENTREGA = """
SELECT NRO_PEDIDO, NUM_SEGUIMIENTO, TALON_PED 
FROM SEIN_TABLA_TEMPORAL_SCRIPT
WHERE TALON_PED = '99'
AND METODO_ENVIO = 'FLEX'
AND NUM_SEGUIMIENTO IS NOT NULL
AND (estadoIdEnvio IS NULL OR estadoIdEnvio NOT IN('3','4','19','23'))
AND NOT EXISTS (
    SELECT 1 FROM RO_T_ESTADO_PEDIDOS_ECOMMERCE 
    WHERE NRO_PEDIDO = SEIN_TABLA_TEMPORAL_SCRIPT.NRO_PEDIDO 
    AND TALON_PED = SEIN_TABLA_TEMPORAL_SCRIPT.TALON_PED 
    AND ENTREGADO = 1
)
ORDER BY NRO_PEDIDO DESC
"""

# Actualizar número de seguimiento en SEIN_TABLA_TEMPORAL_SCRIPT
QRY_UPDATE_NUM_SEGUIMIENTO = """
UPDATE SEIN_TABLA_TEMPORAL_SCRIPT 
SET NUM_SEGUIMIENTO = ?
WHERE NRO_PEDIDO = ? AND TALON_PED = CAST(? AS INT)
"""

# Actualizar estado de envío en SEIN_TABLA_TEMPORAL_SCRIPT
QRY_UPDATE_ESTADO_ENVIO = """
UPDATE SEIN_TABLA_TEMPORAL_SCRIPT 
SET estadoEnvio = ?, 
    estadoIdEnvio = ?, 
    fechaEstadoEnvio = ?
WHERE NRO_PEDIDO = ? AND TALON_PED = CAST(? AS INT)
"""

# Actualizar estado de pedidos entregados en RO_T_ESTADO_PEDIDOS_ECOMMERCE
QRY_UPDATE_ENTREGADO = """
UPDATE RO_T_ESTADO_PEDIDOS_ECOMMERCE 
SET ENTREGADO = 1, FECHA_ENTREGADO = ?
WHERE NRO_PEDIDO = ? AND TALON_PED = CAST(? AS INT)
"""

# Consulta para verificar si el pedido existe en RO_T_ESTADO_PEDIDOS_ECOMMERCE
QRY_CHECK_PEDIDO_ECOMMERCE = """
SELECT COUNT(*) as count
FROM RO_T_ESTADO_PEDIDOS_ECOMMERCE
WHERE NRO_PEDIDO = ? AND TALON_PED = CAST(? AS INT)
"""

# Consulta para obtener un pedido específico por número de seguimiento
QRY_GET_PEDIDO_BY_SEGUIMIENTO = """
SELECT NRO_PEDIDO, NUM_SEGUIMIENTO, TALON_PED, estadoEnvio, estadoIdEnvio
FROM SEIN_TABLA_TEMPORAL_SCRIPT
WHERE NUM_SEGUIMIENTO = ? 
AND METODO_ENVIO = 'FLEX'
"""